site_name: Demo Mkdocs Site
repo_url: https://github.com/AllenInstitute/DemoMkdocsSite/
site_url: https://demo_mkdocssite.alleninstitute.github.io/
nav: 
  - Home: "index.md"
  - Services: 
    - GraphQL API: "!include ./DemoMkdocsGraphQl/mkdocs.yml"
    - REST API: "!include ./DemoMkdocsOpenAPI/mkdocs.yml"
    - Python Library: "!include ./DemoMkdocsPython/mkdocs.yml"

plugins:
  - search
  - monorepo
  - neoteroi.mkdocsoad:
      use_pymdownx: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx 
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme: material