name: deploy

on:
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.DEMO_ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Mkdocs Dependencies
        run: |
          python -m pip install -r docs/requirements.txt
          python -m pip install -r DemoMkdocsGraphQl/docs/requirements.txt
          python -m pip install -r DemoMkDocsOpenAPI/docs/requirements.txt
          python -m pip install -r DemoMkdocsPython/docs/requirements.txt
          python -m pip install DemoMkdocsPython/src/example_module

      - name: Build GH Pages
        run: mkdocs gh-deploy --force --config-file ./mkdocs.yml